### PR TITLE
Update to ash 0.38

### PR DESCRIPTION
**Pull request by realmayus**
Update the ash package's ash version to 0.38.
I'm not sure how to update the version of `gpu-alloc-ash` as it seems to be synced with the `gpu-alloc` package.

### CODE REVIEW

**Review by zakarumych — APPROVED** [review]
This looks alright.

No need to update gpu-alloc itself, they both communicate only via gpu-alloc-types that stay the same

**Comment by realmayus** [comment]
Okay, shouldn't I bump the version of gpu-alloc-ash to 0.6.1 though?

**Comment by zakarumych** [comment]
You've changed minor version of ash, so bump minor version of crate.

**Comment by zakarumych** [comment]
To 0.7.0
Or users of ash 0.37 will update to incompatible version of gpu-alloc-ash

**Comment by zakarumych** [comment]
I've added changes so it would pass checks in #77

**Pull request closed without merging**
