### PR TITLE
Fix freelist

### PR DESCRIPTION
**Pull request by zakarumych**

### CODE REVIEW

**Comment by VincentFTS** [comment]
I still get a second memory allocation that should not happen, even with the just pushed commit.

**Comment by zakarumych** [comment]
Did you enable `"freelist"` feature?

**Comment by VincentFTS** [comment]
My bad, no more avoidable allocations here, good job !!
However, I get `panicked at 'attempt to subtract with overflow', gpu-alloc/src/freelist.rs:177:21` when I close my window.

**Comment by zakarumych** [comment]
Right. I've copied a piece of code where return statements prevented block size to be added to `total` field. Should be fixed now

**Comment by VincentFTS** [comment]
I still get the panic (at line 175).

**Comment by zakarumych** [comment]
I wonder why my example can't find any of these problems, yet I continue seeing issues causing them ^_^

**Comment by VincentFTS** [comment]
Great job !! Sounds good here !!

**Comment by VincentFTS** [comment]
This is needed to fix gfx-rs/wgpu#1242.
Will you release a new version soon ?

**Comment by zakarumych** [comment]
Thanks for providing test case.

**Comment by kvark** [comment]
It's scary to see how much this PR was changing in flight. 
This crate needs more tests, fuzzying, and other means of ensuring correctness.

**Comment by zakarumych** [comment]
@kvark I totally agree with you. There's few simple tests, but they are clearly not enough.

**Pull request merged**
