### PR TITLE
Fix logical errors in sub-allocators

### PR DESCRIPTION
**Pull request by zakarumych**
Successfully runs all wgpu examples

### CODE REVIEW

**Comment by kvark** [comment]
Amazing work! When is this landing? :)

**Comment by zakarumych** [comment]
ETA - this weekend.

**Comment by kvark** [comment]
Hitting this assertion in `cargo test` within `wgpu` once I start calling the newly added `cleanup`:
> "All blocks must be deallocated before cleanup"

Could you double-check if the second assertion in `cleanup` is valid?

**Comment by zakarumych** [comment]
I didn't hit it. But `cargo test` fails on dx12 because it reports that `max_memory_allocation_count = 0` so `gpu-alloc` cannot allocate anything.

**Comment by zakarumych** [comment]
I fixed error that was causing assert to panic.

**Pull request merged**
